name: Build Wheels

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        #os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-14]
        os: [macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Only run install_dep.sh on macos system
      - name: Install dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          bash scripts/install_deps.sh

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.23.3

      - name: Get macos version
        if: startsWith(matrix.os, 'macos')
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | cut -d '.' -f 1-2)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET={{ env.MACOSX_DEPLOYMENT_TARGET }}"

      - name: Setup tmate session
        if: false
        uses: mxschmitt/action-tmate@v3

      - name: Build wheels
        run: |
          if [[ "${{matrix.os}}" == macos* ]]; then
            source ~/.graphscope_env
          fi
          python3 -m cibuildwheel ./tools/python_bind --output-dir wheelhouse
        env:
          # use macos version as the target
          CIBW_ENVIRONMENT_MACOS: "MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl