name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-14, macos-15]

    steps:
      - uses: actions/checkout@v4

      - name: Setup tmate session
        if: false
        uses: mxschmitt/action-tmate@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        with:
           package-dir: tools/python_bind
        #   output-dir: wheelhouse
           config-file: "tools/python_bind/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl